baseURL = "https://www.brennanmacaig.com"
languageCode = "en-us"
title = "Brennan Macaig"
theme = "hermit"

pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 20 # Limit RSS to last 20 items.
copyright = "Copyright (C) Brenann Macaig 2020. All rights reserved." # RSS only
enableEmoji = true
# googleAnalytics = "SOME-CODE-HERE"

[author]
    name = "Brennan Macaig"

[taxonomies]
    tag = "tags"

[params]
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "01-02-2006"
    dateformNumTime = "01-02-2006 15:04 EST"

    themeColor = "#494f5c"
    homeSubtitle = "Site Reliability Engineer - Full Stack Developer - Student - Mentor"
    # bgImg = "" # gradient for background coming soon.

    footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a> &#183 <a href="https://github.com/brennan-macaig/personal-website" target="_blank" rel="noopener">Hack this on GitHub</a>'

    relatedPosts = true

    code_copy_button = true

    # Social Icons
    [[params.social]]
        name = "github"
        url = "https://github.com/brennan-macaig"
    
    [[params.social]]
        name = "instagram"
        url = "https://instagram.com/brennanmacaig"
    
    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/brennan_macaig"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/brennan-macaig/"

[menu]

    [[menu.main]]
        name = "Blog"
        url = "posts/"
        weight = 10

    [[menu.main]]
        name = "About"
        url = "about/"
        weight = 10
    
    [[menu.main]]
        name = "Contact Me"
        url = "contact/"
        weight = 10

    [[menu.main]]
        name = "Resume"
        url = "/resume.pdf"
        weight = 10
    
        