baseURL = "https://www.brennanmacaig.com"
languageCode = "en-us"
title = "Brennan Macaig"
theme = "hugo-coder"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true

[params]
  author = "Brennan Macaig"
  info = "Site Reliability Engineer - Full Stack Developer - Student - Mentor"
  description = "Site Reliability Engineer - Full Stack Developer - Student - Mentor"
  keywords = "blog,developer,personal"
  avatarurl = "static/me.png"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020
  colorScheme = "dark"
  hidecolorschemetoggle = false
  
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/brennan-macaig"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/brennan-macaig/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/brennan_macaig"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://instagram.com/brennanmacaig"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/brennan-macaig/"

# Menu links
[[menu.main]]
  name = "Blog"
  url = "posts/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 1
    
[[menu.main]]
  name = "Contact Me"
  url = "contact/"
  weight = 1

[[menu.main]]
  name = "Resume (PDF)"
  url = "/resume.pdf"
  weight = 1
